export const projectsDetails = [
  {
    id: 1,
    name: 'Apartment in Berlin',
    start: '12.2012',
    type: 'Investment in real estate',
  },
  {
    id: 2,
    name: 'Apartment in Aschheim',
    start: '03.2015',
    finish: '05.2020',
    type: 'Investment in real estate',
  },
  {
    id: 3,
    name: 'JT company in Germany',
    start: '04.2015',
    finish: '05.2020',
    type: 'IT company',
  },
  {
    id: 4,
    name: 'Toner.Expert',
    start: '11.2016',
    finish: '03.2018',
    type: 'IT company',
  },
  {
    id: 5,
    name: 'Haus in Kufstein',
    start: '09.2019',
    type: 'Investment in real estate',
  },
  {
    id: 6,
    name: 'Haus in Waldkraiburg',
    start: '04.2020',
    type: 'Investment in real estate',
  },
  {
    id: 7,
    name: 'Apartment in Vilnius',
    start: '01.2022',
    type: 'Investment in real estate',
  },
  {
    id: 8,
    name: 'Apartment in Vilnius',
    start: '01.2022',
    type: 'Investment in real estate',
  },
  {
    id: 9,
    name: 'FaceAR',
    start: '06.2023',
    type: 'IT company',
    link: 'http://facear.io',
  },
];
